# Generated by Django 4.1.3 on 2022-11-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'کد اعتبار سنجی', 'verbose_name_plural': 'کد های اعتبار سنجی'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل مدرس', 'verbose_name_plural': 'پروفایل مدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
    ]
