# Generated by Django 4.1.3 on 2022-11-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_comment_course_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
    ]
