# Generated by Django 4.1.3 on 2022-11-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.ManyToManyField(to='blog.ipaddress'),
        ),
    ]
