# Generated by Django 4.1.3 on 2022-11-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ipaddress_remove_blog_view_blog_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آدرس IP', 'verbose_name_plural': 'آدرس های IP'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='view',
            field=models.ManyToManyField(blank=True, null=True, to='blog.ipaddress'),
        ),
    ]
