# Generated by Django 4.1.3 on 2022-11-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_contactus_options_alter_teach_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='body',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='category',
            field=models.CharField(choices=[('mobile_developer', 'برنامه نویسی موبایل'), ('web_developer', 'برنامه نویسی وب'), ('graphics', 'گرافیک'), ('AI', 'هوش مصنوعی')], max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='link',
            field=models.URLField(max_length=120, verbose_name='لینک ویدئو'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='title',
            field=models.CharField(max_length=80, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
